<script>
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
                form.action = url;
            }
            var e = null;
            if(!url){
                url = $j('#product_addtocart_form').attr('action');
            }
            url = url.replace("checkout/cart","ajax/cart"); // New Code
            var data = $j('#product_addtocart_form').serialize();
            data += '&isAjax=1';
            $j('#ajax_loader').show();
            try {
                $j.ajax({
                    url: url,
                    dataType: 'json',
                    type : 'post',
                    data: data,
                    success: function(data){
                        $j('#ajax_loader').hide();
                        $j('.header-minicart').html(data.minicart);
                        $j('#header-account').html(data.toplink);

                        $j('<ul class="messages">' +
                                '<li class="'+data.status+'-msg">' +
                                    '<ul>' +
                                        '<li><span>'+data.message+'</span></li>' +
                                    '</ul>' +
                                '</li>' +
                            '</ul>')
                            .insertAfter('#header-nav');
                        setTimeout(function(){$j('.messages').fadeOut('fast')},3000);
                    }
                });
            } catch (e) {
            }
//End of our new ajax code
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }
        }
    }.bind(productAddToCartForm);

    var skipContents = $j('.skip-content');
    var skipLinks = $j('.header-minicart a.skip-link');

    $j(document).on('click','.header-minicart a.skip-link', function (e) {
        e.preventDefault();

        var self = $j(this);
        // Use the data-target-element attribute, if it exists. Fall back to href.
        var target = self.attr('data-target-element') ? self.attr('data-target-element') : self.attr('href');
        console.log(target);

        // Get target element
        var elem = $j(target);

        // Check if stub is open
        var isSkipContentOpen = elem.hasClass('skip-active') ? 1 : 0;

        // Hide all stubs
        var parent = $j(this).parents('.skip-content');
        var link = parent.siblings('.skip-link');

        parent.removeClass('skip-active');
        link.removeClass('skip-active');

        e.preventDefault();

        // Toggle stubs
        if (isSkipContentOpen) {
            parent.removeClass('skip-active');
            link.removeClass('skip-active');
        } else {
            self.addClass('skip-active');
            elem.addClass('skip-active');
        }
    });

    $j(document).on('click', '.skip-link-close', function(e) {
        var parent = $j(this).parents('.skip-content');
        var link = parent.siblings('.skip-link');

        parent.removeClass('skip-active');
        link.removeClass('skip-active');

        e.preventDefault();
    });
</script>