<h1>Create post</h1>
<form id="create" action="<?=Mage::getUrl('blog/post/save')?>" method="post">
    <p>Title:</p> <input type="text" class="input-text required-entry validate-no-html-tags validate-length" name="title">
    <br>
    <p>Description:</p> <textarea rows="7" name="description" class="input-text required-entry validate-no-html-tags"></textarea>
    <br><br>
    <button type="submit">Add post</button>
</form>

<script>
    myForm = new VarienForm('create');
</script>