
<?php $post = $this->getPost(); ?>
<h1><?=empty($post->getId()) ? 'Create post' : 'Update post'?></h1>
<form id="update" action="<?=Mage::getUrl('blog/post/save')?>" method="post" enctype="multipart/form-data">
    <p>Title:</p> <input type="text" class="input-text required-entry validate-no-html-tags validate-length" value="<?=$post->getTitle()?>" name="title">
    <br>
    <p>Description:</p> <textarea rows="7" name="description" value="" class="input-text required-entry validate-no-html-tags"><?=$post->getPost()?></textarea>
    <br><br>
    <p>Select image: <input type="file" name="image" id="image" title="<?php echo $this->__('Image') ?>" class="input-file" /></p>
    <br><br>
    <input type="hidden" name="post_id" value="<?=$post->getId()?>">
    <button type="submit">Save post</button>
</form>

<script>
    myForm = new VarienForm('update');
</script>