<h1>List posts:</h1>
<a style="float: right;" href="<?=Mage::getUrl('blog/post/create')?>">Add new post</a>
<?php
foreach($this->getAllPosts() as $post){ ?>
    <h2><a href="<?=Mage::getUrl('blog/post/view/') . 'id/' . $post->getBlogpostId()?>"><?=$post->getTitle()?></a></h2>
    <p>Author: <?=$post->getFirstName() . ' ' . $post->getLastName()?></p>
    <p>Date create: <?=$post->getDateCreate()?></p>
    <p>Description: <?=Mage::helper('core/string')->truncate($post->getPost(), 50);?></p>
    <hr>
    <br>
<?php } ?>
