<?php
$_helper = $this->helper('catalog/output');
$productBlock = $this->getLayout()->createBlock('catalog/product_price');
$post = $this->getPost();
$_products = $post->getProducts();
if ($_products->count()): ?>
    <div class="block block-list block-viewed">
        <div class="block-title">
            <h1><span><?php echo $this->__('Post Products:') ?></span></h1>
        </div>
        <div class="category-products">
            <?php
            $_collectionSize = $_products->count();
            $_columnCount = 4; ?>
            <ul class="products-grid products-grid--max-<?=$_columnCount?>-col">
                <?php $i=0; foreach ($_products as $_product): ?>
                    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <?php $_imgSize = 210; ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a>
                        <div class="product-info">
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                            <?php echo $productBlock->getPriceHtml($_product, true) ?>
                            <?=Mage::helper('core/string')->truncate($_product->getShortDescription(), 70);?>
                        </div>
                    </li>
                <?php endforeach ?>
            </ul>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        </div>
    </div>
<?php endif; ?>