<?php
$post = $this->getPost();
?>

<h1><?=$post->getTitle()?></h1>
<?php if($this->checkPost()):  ?>
    <p>
        <a href="<?=Mage::getUrl('blog/post/update/') . 'id/' . $post->getId()?> ">Edit post |</a>
        <a href="<?=Mage::getUrl('blog/post/delete/') . 'id/' . $post->getId()?> "> Delete</a>
    </p>
<?php endif; ?>
<p>Author: <?=$post->getFirstName() . ' ' . $post->getLastName()?></p>
<p>Date create: <?=$post->getDateCreate() ?></p>
<?php if($post->getImage()) { ?>
    <br>
    <div style="text-align:center"><img style="width:100%" src="<?=Mage::getUrl('media/') . $post->getImage()?> "></div>
<?php } ?>
<br>
<p><?=$post->getPost()?></p>
<br>
